# This is a basic workflow to help you get started with Actions

name: CI-CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: Docker build and push
        uses: docker/build-push-action@v2.10.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            guisilveira/rotten-potatoes:latest
            guisilveira/rotten-potatoes:${{ github.run_number }}
  cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Kubernetes context
        uses: Azure/k8s-set-context@v2
        with:
          kubeconfig: ${{ secrets.K8S_CONFIG }}
      - name: Deploy to K8S
        uses: Azure/k8s-deploy@v3.0
        with:
          images: guisilveira/rotten-potatoes:${{ github.run_number }}
          manifests: |
            k8s/deployment.yaml
        
